numFeatures = height(Xtrain{1}); % same as input size...
numHiddenUnits = 50;
numClasses = 2;
layers = [ ...
    sequenceInputLayer(numFeatures)
    lstmLayer(numHiddenUnits)
    lstmLayer(numHiddenUnits,'OutputMode','last')
    dropoutLayer(.5)
    fullyConnectedLayer(30)
    reluLayer
    fullyConnectedLayer(1)
    regressionLayer];
% specify training options
maxEpochs = 70;
miniBatchSize = 2^5;
options = trainingOptions('adam', ...
    'ExecutionEnvironment','cpu', ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'GradientThreshold',1, ...
    'Plots','training-progress',...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.5, ...
    'LearnRateDropPeriod',5, ...
    'initialLearnRate',0.002, ... 
    'OutputFcn',@(info)myCostumOutputFcn(info,5*3600,inf));
