numFeatures = 30;
numClasses = 2;
layers = [...
    sequenceInputLayer(numFeatures)
    lstmLayer(50)
    lstmLayer(50,'OutputMode','last')
    dropoutLayer(.5)
    fullyConnectedLayer(30)
    fullyConnectedLayer(numClasses)
    softmaxLayer
    classificationLayer];
    % specify training options
    maxEpochs = 70;
    miniBatchSize = 2^5;
options = trainingOptions('adam', ...
    'ExecutionEnvironment','cpu', ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'GradientThreshold',1, ...
    'Plots','training-progress',...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropFactor',0.5, ...
    'LearnRateDropPeriod',5,...
    'initialLearnRate',0.002, ...   
    'OutputFcn',@(info)myCostumOutputFcn(info,270*60,inf));
